arm:
  kinematics_solver: kdl_kinematics_plugin/KDLKinematicsPlugin
  kinematics_solver_timeout: 0.05
  kinematics_solver_attempts: 20
  goal_joint_tolerance: 0.001
  goal_position_tolerance: 0.001
  goal_orientation_tolerance: 0.001