moveit_controller_manager: moveit_simple_controller_manager/MoveItSimpleControllerManager
controller_names: [traj_controller]

traj_controller:
  type: FollowJointTrajectory
  joints: [rev1, rev2, rev3, rev4, rev5, rev6, rev7]
  action_ns: follow_joint_trajectory
  default: true
