_wandb:
    value:
        cli_version: 0.24.1
        e:
            sqh5jpsnacfgdlqxuni7r9rfs64ik1f0:
                args:
                    - --policy.path=lerobot/smolvla_base
                    - --dataset.repo_id=openarm_vla
                    - --dataset.root=/home/highsky/openarm_vla
                    - '--policy.input_features={"observation.state": {"type": "STATE", "shape": [16]}, "observation.images.camera1": {"type": "VISUAL", "shape": [3, 256, 256]}, "observation.images.camera2": {"type": "VISUAL", "shape": [3, 256, 256]}, "observation.images.camera3": {"type": "VISUAL", "shape": [3, 256, 256]}}'
                    - '--policy.output_features={"action": {"type": "ACTION", "shape": [16]}}'
                    - '--rename_map={"observation.images.top": "observation.images.camera1", "observation.images.wrist_left": "observation.images.camera2", "observation.images.wrist_right": "observation.images.camera3"}'
                    - --batch_size=4
                    - --steps=20000
                    - --output_dir=outputs/train/smolvla_openarm_16dim
                    - --job_name=smolvla_openarm_16dim_training
                    - --policy.device=cuda
                    - --wandb.enable=true
                    - --policy.push_to_hub=false
                cpu_count: 14
                cpu_count_logical: 20
                cudaVersion: "13.0"
                disk:
                    /:
                        total: "789584322560"
                        used: "276145573888"
                executable: /home/highsky/anaconda3/envs/lerobot/bin/python3.10
                git:
                    commit: aea253bc6bc3d8ab9952ea9882df150595405f58
                    remote: https://github.com/Highsky7/lerobot_FMVLA.git
                gpu: NVIDIA GeForce RTX 4060 Laptop GPU
                gpu_count: 1
                gpu_nvidia:
                    - architecture: Ada
                      cudaCores: 3072
                      memoryTotal: "8585740288"
                      name: NVIDIA GeForce RTX 4060 Laptop GPU
                      uuid: GPU-d9963481-465a-a010-7d70-43522f9d77f0
                host: highsky-Legion-Slim-5-16IRH8
                memory:
                    total: "16550977536"
                os: Linux-6.8.0-90-generic-x86_64-with-glibc2.35
                program: /home/highsky/anaconda3/envs/lerobot/bin/lerobot-train
                python: CPython 3.10.12
                root: outputs/train/smolvla_openarm_16dim
                startedAt: "2026-02-04T18:04:08.789680Z"
                writerId: sqh5jpsnacfgdlqxuni7r9rfs64ik1f0
        m: []
        python_version: 3.10.12
        t:
            "1":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 83
            "2":
                - 1
                - 5
                - 11
                - 41
                - 49
                - 51
                - 53
                - 71
                - 83
            "3":
                - 13
                - 15
                - 16
                - 61
            "4": 3.10.12
            "5": 0.24.1
            "6": 4.57.3
            "10":
                - 21
            "12": 0.24.1
            "13": linux-x86_64
batch_size:
    value: 4
checkpoint_path:
    value: null
dataset:
    value:
        episodes: null
        image_transforms:
            enable: false
            max_num_transforms: 3
            random_order: false
            tfs:
                affine:
                    kwargs:
                        degrees:
                            - -5
                            - 5
                        translate:
                            - 0.05
                            - 0.05
                    type: RandomAffine
                    weight: 1
                brightness:
                    kwargs:
                        brightness:
                            - 0.8
                            - 1.2
                    type: ColorJitter
                    weight: 1
                contrast:
                    kwargs:
                        contrast:
                            - 0.8
                            - 1.2
                    type: ColorJitter
                    weight: 1
                hue:
                    kwargs:
                        hue:
                            - -0.05
                            - 0.05
                    type: ColorJitter
                    weight: 1
                saturation:
                    kwargs:
                        saturation:
                            - 0.5
                            - 1.5
                    type: ColorJitter
                    weight: 1
                sharpness:
                    kwargs:
                        sharpness:
                            - 0.5
                            - 1.5
                    type: SharpnessJitter
                    weight: 1
        repo_id: openarm_vla
        revision: null
        root: /home/highsky/openarm_vla
        streaming: false
        use_imagenet_stats: true
        video_backend: torchcodec
env:
    value: null
eval:
    value:
        batch_size: 50
        n_episodes: 50
        use_async_envs: false
eval_freq:
    value: 20000
job_name:
    value: smolvla_openarm_16dim_training
log_freq:
    value: 200
num_workers:
    value: 4
optimizer:
    value:
        betas:
            - 0.9
            - 0.95
        eps: 1e-08
        grad_clip_norm: 10
        lr: 0.0001
        type: adamw
        weight_decay: 1e-10
output_dir:
    value: outputs/train/smolvla_openarm_16dim
peft:
    value: null
policy:
    value:
        adapt_to_pi_aloha: false
        add_image_special_tokens: false
        attention_mode: cross_attn
        chunk_size: 50
        device: cuda
        empty_cameras: 0
        expert_width_multiplier: 0.75
        freeze_vision_encoder: true
        input_features:
            observation.images.camera1:
                shape:
                    - 3
                    - 256
                    - 256
                type: VISUAL
            observation.images.camera2:
                shape:
                    - 3
                    - 256
                    - 256
                type: VISUAL
            observation.images.camera3:
                shape:
                    - 3
                    - 256
                    - 256
                type: VISUAL
            observation.state:
                shape:
                    - 16
                type: STATE
        license: null
        load_vlm_weights: true
        max_action_dim: 32
        max_period: 4
        max_state_dim: 32
        min_period: 0.004
        n_action_steps: 50
        n_obs_steps: 1
        normalization_mapping:
            ACTION: MEAN_STD
            STATE: MEAN_STD
            VISUAL: IDENTITY
        num_expert_layers: 0
        num_steps: 10
        num_vlm_layers: 16
        optimizer_betas:
            - 0.9
            - 0.95
        optimizer_eps: 1e-08
        optimizer_grad_clip_norm: 10
        optimizer_lr: 0.0001
        optimizer_weight_decay: 1e-10
        output_features:
            action:
                shape:
                    - 16
                type: ACTION
        pad_language_to: max_length
        prefix_length: 0
        pretrained_path: lerobot/smolvla_base
        private: null
        push_to_hub: false
        repo_id: null
        resize_imgs_with_padding:
            - 512
            - 512
        rtc_config: null
        scheduler_decay_lr: 2.5e-06
        scheduler_decay_steps: 30000
        scheduler_warmup_steps: 1000
        self_attn_every_n_layers: 2
        tags: null
        tokenizer_max_length: 48
        train_expert_only: true
        train_state_proj: true
        type: smolvla
        use_amp: false
        use_cache: true
        use_delta_joint_actions_aloha: false
        use_peft: false
        vlm_model_name: HuggingFaceTB/SmolVLM2-500M-Video-Instruct
rabc_epsilon:
    value: 1e-06
rabc_head_mode:
    value: sparse
rabc_kappa:
    value: 0.01
rabc_progress_path:
    value: null
rename_map:
    value:
        observation.images.top: observation.images.camera1
        observation.images.wrist_left: observation.images.camera2
        observation.images.wrist_right: observation.images.camera3
resume:
    value: false
save_checkpoint:
    value: true
save_freq:
    value: 20000
scheduler:
    value:
        decay_lr: 2.5e-06
        num_decay_steps: 30000
        num_warmup_steps: 1000
        peak_lr: 0.0001
        type: cosine_decay_with_warmup
seed:
    value: 1000
steps:
    value: 20000
tolerance_s:
    value: 0.0001
use_policy_training_preset:
    value: true
use_rabc:
    value: false
wandb:
    value:
        disable_artifact: false
        enable: true
        entity: null
        mode: null
        notes: null
        project: lerobot
        run_id: null
